### ISSUE TITLE
Moving np.argsort out of numba-compiled func.

### ISSUE THREAD

**Issue by fingoldo** [diditforlulz273/fastauc#8]
Hi, please consider moving np.argsort out of numba-compiled func, as njitting argsort is known for slowing it down twice (still as of 2023, unfortunately). That makes Numba version faster than C version :-)

smth like

```
def optimized_auc(y_true: np.array, y_score: np.array) -> float:
    desc_score_indices = np.argsort(y_score,)[::-1]
    return fast_numba_auc_nonw(y_true=y_true, y_score=y_score, desc_score_indices=desc_score_indices)
```

My tests on 8M float32 array:

> %timeit fast_auc.fast_auc(y_true=Y_val.values, y_score=probs[:, 1])
> 392 ms ± 2.79 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> 
> %timeit fast_auc.fast_numba_auc(y_true=Y_val.values, y_score=probs[:, 1])
> 672 ms ± 2.28 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> 
> %timeit optimized_auc(y_true=Y_val.values, y_score=probs[:, 1])
> 338 ms ± 3.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

No need to hardcode mergesort, as well.

**Comment by diditforlulz273** [comment]
@fingoldo okay looks correct, plz. make a PR if you want to add it.

**Comment by fingoldo** [comment]
Привет, запостил PR, у меня изменения снизили время расчёта numba-варианта в demo.py с 0.33 и 0.36 до 
 0.22 и 0.26 сек. Документацию и график я не правил, т.к. не нашел в репе скрипта строящего график, оставляю это на усмотрение автора. Что интересно, у меня после установки fastauc сразу Numba-версия обходила сишную:

> python numba fast AUC 10000 calls time = 0.3316957180000024
> C++ fast AUC 10000 calls time = 0.40951755000000034

Кстати, у меня улучшить скорость сишного кода помогло удаление march и добавление Ofast флага:
g++ -shared -O3 -Ofast cpp_auc.cpp -o cpp_auc.so
если это подтвердится, возможно, надо поменять инструкцию в доке.

Я заметил, что в оригинале что-то не так с сишным и "чисто питоновским" вариантами взвешенной auc - не сходятся цифры.

Calculation with sample weights
sklearn AUC = 0.8253851783670886
python fast AUC = 0.82538**66173380757**
python numba fast AUC = 0.8253851783670886
C++ fast AUC = 0.8253851**532936096**

**Comment by diditforlulz273** [comment]
Merged your PR, thanks!
Changing O3 to Ofast and removing march=native gave no effect for me - these keys are highly platform-dependent and do not always yield any performance upgrades. I'll stick with what's here now.

Regarding AUC differences in the 6th digit - I don't care, I believe there's no real problem besides some float32/float64 rounding somewhere deep inside.
